=== AleksGavs/HTML_XML/XML/Lab3/resume_complex_XML.xsd
<?xmlversion = "1.0" encoding = "utf-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="resume">
		<xs:complexType>
			<xs:sequence>
				<xs:element name = "HigherEducation">
					<xs:complexType>
						<xs:sequence>
							<xs:element name = "Candidate" minOccurs = "1" maxOccurs = "unbounded" type="CandidateData"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name = "SecondaryEducation">
					<xs:complexType>
						<xs:sequence>
							<xs:element name = "Candidate" minOccurs = "1" maxOccurs = "unbounded" type="CandidateData"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element> 
	
	
	<xs:complexType name="CandidateData">
		<xs:sequence>
				<xs:element	name = "Name" type="xs:string"/>	
				<xs:element	name = "Surname" type="xs:string"/>	
				<xs:element	name = "Patronym" type="xs:string"/>	
				<xs:element	name = "CurrentJob" type="xs:string"/>	
				<xs:element	name = "CurrentPosition" type="xs:string"/>	
				<xs:element	name = "DateOfBirth">
						<xs:simpleType>
							<xs:restriction base="xs:date">
								<xs:minInclusive value="1947-01-01"/>
								<xs:maxInclusive value="1992-01-01"/>
							</xs:restriction>
						</xs:simpleType>
				</xs:element>	
				<xs:element name = "Age" type = "AgeType" />
				<xs:element	name = "Education">
						<xs:simpleType>
							<xs:restriction base = "xs:string">
								<xs:enumeration value="Высшее"/>
								<xs:enumeration value="Среднее" />
							</xs:restriction>
						</xs:simpleType>	
				</xs:element>					
				<xs:element	name = "Address" type="xs:string"/>					
				<xs:element	name = "PhoneNumber">
					<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:pattern value="[0-9]{3}-[0-9]{2}-[0-9]{2}"/>
							</xs:restriction>
					</xs:simpleType>
				</xs:element>					
				<xs:element	name = "FamilyStatus">
						<xs:simpleType>
							<xs:restriction base = "xs:string">
								<xs:enumeration value="Женат"/>
								<xs:enumeration value="Замужем" />
								<xs:enumeration value="Не замужем" />
								<xs:enumeration value="Не женат"/>
							</xs:restriction>
						</xs:simpleType>
				</xs:element>
				<xs:element	name = "DesiredIncome" type="xs:integer"/>	
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>
	
	
	<xs:simpleType name = "AgeType">		
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="20"/>
				<xs:maxInclusive value="65"/>
			</xs:restriction>		
	</xs:simpleType>			
	
</xs:schema>

=== AleksGavs/HTML_XML/XML/Lab3/resume_complex.xml
<?xmlversion = "1.0" encoding = "utf-8" ?>
<resume xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/E:/ИТМО/05 HTML и XML/Практика выполненное/HTML_CSS_XML/XML/Lab3/resume_complex_XML.xsd">

<HigherEducation>
	<Candidate id = "C101">
		<Name>Павел</Name>
		<Surname>Чичиков</Surname>
		<Patronym>Иванович</Patronym>
		<CurrentJob>ООО "Душевная компания"</CurrentJob>
		<CurrentPosition>Чиновник</CurrentPosition>
		<DateOfBirth>1989-07-16</DateOfBirth>
		<Age>25</Age>
		<Education>Высшее</Education>
		<Address>ул. Гоголя, д. 25, кв. 12</Address>
		<PhoneNumber>125-44-88</PhoneNumber>
		<FamilyStatus>Женат</FamilyStatus>
		<DesiredIncome>150000</DesiredIncome>
	</Candidate>
	
	<Candidate id = "C121">
		<Name>Родион</Name>
		<Surname>Раскольников</Surname>
		<Patronym>Романович</Patronym>
		<CurrentJob>ОАО "Как срубить бабок"</CurrentJob>
		<CurrentPosition>Лесоруб</CurrentPosition>
		<DateOfBirth>1978-08-02</DateOfBirth>
		<Age>45</Age>
		<Education>Высшее</Education>
		<Address>ул. Достаевского, д. 1, кв. 66</Address>
		<PhoneNumber>258-16-98</PhoneNumber>
		<FamilyStatus>Не женат</FamilyStatus>
		<DesiredIncome>80000</DesiredIncome>
	</Candidate>
</HigherEducation>

<SecondaryEducation>
	<Candidate id = "D095">
		<Name>Анна</Name>
		<Surname>Каренина</Surname>
		<Patronym>Аркадьевна</Patronym>
		<CurrentJob>ОАО "РЖД"</CurrentJob>
		<CurrentPosition>Обходчик ЖД путей</CurrentPosition>
		<DateOfBirth>1991-11-05</DateOfBirth>
		<Age>27</Age>
		<Education>Среднее</Education>
		<Address>ул. Толстого, д. 5, кв. 17</Address>
		<PhoneNumber>425-87-14</PhoneNumber>
		<FamilyStatus>Замужем</FamilyStatus>
		<DesiredIncome>92000</DesiredIncome>
	</Candidate>
	
	<Candidate id = "D012">
		<Name>Юрий</Name>
		<Surname>Живаго</Surname>
		<Patronym>Андреевич</Patronym>
		<CurrentJob>Поликлиника №3</CurrentJob>
		<CurrentPosition>Доктор</CurrentPosition>
		<DateOfBirth>1970-04-01</DateOfBirth>
		<Age>53</Age>
		<Education>Среднее</Education>
		<Address>ул. Пастернака, д. 1, кв. 125</Address>
		<PhoneNumber>147-11-55</PhoneNumber>
		<FamilyStatus>Не женат</FamilyStatus>
		<DesiredIncome>48000</DesiredIncome>
	</Candidate>
</SecondaryEducation>
</resume>
